image: ruby:2.5

cache:
  paths:
  - vendor/
  
before_script:
  - bundle install --path vendor
  
test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - rm public/*
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master