title: 初心
email: chrisdempewolf@protonmail.com
description: Forever in search of the farther shore.
url: "http://chrisdempewolf.com"
github_username:  dempe
permalink: /:title.html
markdown: kramdown
safe: true
timezone: America/Los_Angeles
encoding: utf-8
show_drafts: false
sass:
  sass_dir: ./_sass
