baseURL = "https://chrisdempewolf.com"
languageCode = "en-us"
title = "Shoshin"
theme = "mytheme"

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 3
