name: CI

on:
  push:
    branches: 
      - release/*

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.12.0'
